### ISSUE TITLE
Get approval from spaceduck creator to add theme to vs code marketplace & open vsx registry

### ISSUE THREAD

**Issue by yylian** [tathran/spaceduck-vscode#1]
Hey, I'm sorry to bother you, but I am interested in this too, is there something I can do, or can you give a status update on this?

**Comment by ghost** [comment]
Hey @yylian no apologies needed!

I added the theme to the marketplace: <https://marketplace.visualstudio.com/items?itemName=spaceduck-vscode.spaceduck>

for other things that need to be done, I may be a little slower, e.g. terminal colors. You are welcome to create a PR for those type of things if you are interested.
