### ISSUE TITLE
C# syntax support?

### ISSUE THREAD

**Issue by pyrbin** [tathran/spaceduck-vscode#10]
Would it be possible to support other languages like C#?

The highlighting is kinda broken atm, see below:
![image](https://user-images.githubusercontent.com/31902695/130069375-74d42f28-9490-44cc-adf5-15105ff44625.png)

**Comment by spcbfr** [comment]
Hey, I'll work on it this afternoon and I will notify you once its done !

**Comment by spcbfr** [comment]
Hey @pyrbin, I just pushed and published to the marketplace. you can update the theme and tell me what you think !

**Comment by pyrbin** [comment]
Looking good!

Only thing I can notice is that C# `struct` & `class` doesn't follow the same styling as classes in JS/TS.

`C#`

![Capture](https://user-images.githubusercontent.com/31902695/130121136-8e083148-7ae9-43b6-9550-c357af890fd7.PNG)

`Typescript`

![ssCapture](https://user-images.githubusercontent.com/31902695/130121214-56973bdf-7752-46f0-a6cb-024ef97ed704.PNG)

**Comment by pyrbin** [comment]
And seems to be some inconsistency with preprocessor directives.

Should be same color imo
![image](https://user-images.githubusercontent.com/31902695/130123689-161aa6ee-5393-4334-989e-a1eaa42d28f0.png)
