### ISSUE TITLE
[Request] High contrast variation

### ISSUE THREAD

**Issue by tranzystorekk** [tathran/spaceduck-vscode#3]
I'd like to get to know with spaceduck more, but currently the editor and the rest of the UI blend together too much.

A good example is [Community Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-community-material-theme). There, each theme has a High Contrast variant, as shown below. If spaceduck could similarly have UI colors in a slightly darker shade, that would be sweet 😄

CMT Darker
![obraz](https://user-images.githubusercontent.com/5671049/112199134-226e0b00-8c0e-11eb-8dd3-87cba6f58876.png)

CMT Darker High Contrast
![obraz](https://user-images.githubusercontent.com/5671049/112199229-3ade2580-8c0e-11eb-88f6-04701ee0e340.png)

**Comment by ctrl-dlahr** [comment]
Appreciate the feedback, but I do not want to change the colors so far from the original theme from which this was made. If you did want to tweak the colors slightly, the good news is that is very easy to do. In your settings you can do things like,

```json
"workbench.colorCustomizations": {
        "[spaceduck]": {
            // changes go here
            // "editor.background": "#000000"
        }
    }
```

you can also change the tokens and customize as much as you want,

```json
"editor.tokenColorCustomizations": {
        "[spaceduck]": {
            "textMateRules": [
                {
                    // add more scopes, more tokens, you can even bold fonts here, etc.
                    "scope": "keyword.operator",
                    "settings": {
                        "foreground": "#000000"
                    }
                }
            ]
        }
  }
```

to find out what those tokens are you can even inspect them from your dev tools: <https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide> via `Developer: Inspect Editor Tokens and Scopes`

**Comment by ghost** [comment]
Appreciate the feedback, but I do not want to change the colors so far from the original theme from which this was made. If you did want to tweak the colors slightly, the good news is that is very easy to do. In your settings you can do things like,

```json
"workbench.colorCustomizations": {
        "[spaceduck]": {
            // changes go here
            // "editor.background": "#000000"
        }
    }
```

you can also change the tokens and customize as much as you want,

```json
"editor.tokenColorCustomizations": {
        "[spaceduck]": {
            "textMateRules": [
                {
                    // add more scopes, more tokens, you can even bold fonts here, etc.
                    "scope": "keyword.operator",
                    "settings": {
                        "foreground": "#000000"
                    }
                }
            ]
        }
  }
```

to find out what those tokens are you can even inspect them from your dev tools: <https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide> via `Developer: Inspect Editor Tokens and Scopes`

**Comment by spcbfr** [comment]
hey @tranzystorek-io, I discussed this with the spaceduck theme, and they seem to prefer the high contrast variation, now the vscode theme ships with it out of the box, no need for any extra configuration. just make sure you have [the new theme](https://marketplace.visualstudio.com/items?itemName=YoussefBouzekri.spaceduck) installed !
