### ISSUE TITLE
Tab titles hard to read when using split pane

### ISSUE THREAD

**Issue by bbqben** [tathran/spaceduck-vscode#8]
In VSCode when you split the editor while having multiple tabs open on both, you are not able to read some of the file names on the tabs.

![image](https://user-images.githubusercontent.com/26254566/124513981-ff74fa80-dda9-11eb-8b65-abcdc7ae5499.png)

In the example above, I'm focused on the editor on the right-hand side. You can see how some of the file names can't be read in the tabs on the editor on the left-hand side.

**Comment by spcbfr** [comment]
Hey, thanks for reporting this ! I did not notice this at first since I don't use multiple editors at once in vscode, will fix this.

**Comment by spcbfr** [comment]
@benTranCodes Done, make sure to update to get the latest patch
